apiVersion: v1
kind: Service
metadata:
  labels:
    app: bashar-solar-system
  name: bashar-solar-system
  namespace: _{_NAMESPACE_}_
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: bashar-solar-system 
  type: LoadBalancer